name: dockerhub

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Version being targeted (heads/main for latest or tags/version for versioned release)"
        required: true
        default: "refs/heads/main"
  # push:
  #   branches:
  #     - "main"

jobs:
  dockerhub-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: "Log into registry"
        run: echo "${{ secrets.DOCKERHUB_PASSWORD}}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME}}" --password-stdin
      - name: "Build containers"
        run: bash ./build_containers.sh
        env:
          REF: ${{ github.event.inputs.ref }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: runiac/deploy
          short-description: ${{ github.event.repository.description }}
